pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout Source') {
            steps {
                echo 'git branch: main'              
                echo 'Using credentialsId: github-creds'            
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/yourname/messaging-app.git'
            }
        }

        stage('Set Up Python Env') {
            steps {
                echo 'Creating virtual environment and installing requirements...'
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install --upgrade pip'
                sh './venv/bin/pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests with pytest...'
                sh './venv/bin/pytest --junitxml=report.xml'
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -rf venv'
        }
    }
}

