name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DJANGO_SECRET_KEY: testsecretkey
      DB_NAME: name_db
      DB_USER: nana_u
      DB_PASSWORD: test_pass
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          echo "Running flake8 lint check..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
        continue-on-error: false  # ❌ fail the build on lint errors

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -P3306 --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests with coverage
        run: |
          coverage run manage.py test
          coverage report
          coverage html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/

